# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d8517ed0b2118e4e97454bd2c0470373eba3788d43b38e0ebbe08785828e794b711fe0682228f6bd90337ab942e9584709a019b914a5394ae2cce39c26f2522

test:
  secret_key_base: b59bc610d276fa691fac9388c04d4a8dec5d5a174ae40a528ccf0552353c65d97ba22a1d04708baab33b76d95861bf73304741e8ddf91ec50619da9680c7d368

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
